#!/usr/bin/env bash

# Assumes MYDATA and HOST are set properly
# ??: for some reashon $HOST is empty here (even though its not in the terminal)

# it reads $FILE_LIST_FILE for the list of files

echo "bkpsysconfigs: Backing up the system config files.";

HOST="`cat /proc/sys/kernel/hostname`";
CURR_DIR="`pwd`";
BASE_DIR="$MYDATA/git/configs-git";
DEST_DIR="$BASE_DIR/sys-files/$HOST";
FILE_LIST_FILE="$DEST_DIR/sys-files.list";
count=0

cd "$DEST_DIR";

while read line; do
  # a neat trick (avoids blank lines and comments)
  if [[ ${line:0:1} == "/" ]]; then  # thus a path
    if [[ -e "$line" ]]; then
      DIRNAME="$( dirname "$line" )";
      RELATIVE_DIR="${DIRNAME:1}";

      mkdir -p "${RELATIVE_DIR}";

      CURR_DEST_DIR="$DEST_DIR/$RELATIVE_DIR";

      myConditionalCopy $line $CURR_DEST_DIR;
    else
      echo "DoesNotExist  : '$line'";
    fi
  fi
done < "$FILE_LIST_FILE";

#echo "Copied $count files/directories.";


cd "$CURR_DIR";

