#!/bin/bash

# check if the current folder has jpg files if not, exit

ls *.jpg *.JPG *.jpeg &> /dev/null

if [[ $? == 2 ]]; then
    echo "AD: compress-img: No image files in current folder."
    exit
fi

# process jpg files
compressed=compressed1234
mkdir $compressed

count=0
total=0
error=0
for x in *.jpg *.JPG; do
    ((total++))
done

for x in *.jpg *.JPG; do
    echo -e "Compressing $x"
    jpegoptim -m50 -d $compressed $x
    if [[ $? -ne 0 ]]; then
        echo "$x" >> $compressed/error.log
        ((error++))
    fi
    echo "$x" >> $compressed/success.log
    ((count++))
    echo -e "Compressed  $x"
    echo -e "Done  $count / $total"
done

if [[ $error -eq 0 ]]; then
    echo "SUCCESS"
else
    echo "Error $error"
fi



