#!/usr/bin/env python3

import sys

if len(sys.argv) == 0:
  print("A whitespace(s) col sep is assumed. Enter the column number you want (column numbers start from 1).")
  exit(1)

col = int(sys.argv[1])

for line in sys.stdin:
  words = line.split()
  print(words[col-1])


