#!/bin/bash

DIR=.
cd $DIR
echo -e "\n$>>> $DIR\n"

if [[ ! -z $2 ]]; then
    echo -e "\nAD: Read Only Repository"
    git fetch --all
    git fetch --tags
    git reset --hard origin/master
fi

OUTPUT=$(git status --short)

if [[ ! -z $OUTPUT ]]; then
  echo -e "\nAD: GIT STATUS: Uncommitted changes!!!!"
  git add --all

  if [ "$1" == "" ]; then
    git commit -m 'semiautomated-update'
  else
    git commit -m "$1"
  fi
else
  echo -e "\nAD: GIT STATUS: OK"
fi


echo -e "\nAD: Fetching origin/master."
git fetch origin master

OUTPUT=$(git diff master origin/master)

if [[ -z $OUTPUT ]]; then
    echo "Local state matches origin/master"
    exit
fi

echo -e "\nAD: Local and Remote differ. Merging and Pushing."

# reaches here only when any new content is present

git merge -m "semiautomated-merge" origin/master
git push origin master


