#!/bin/bash

DIR=.
cd $DIR
echo -e "\n$>>> $DIR\n"
git add --all

if [ "$1" == "" ]; then
    git commit -m 'semiautomated-update'
else
    git commit -m "$1"
fi

git fetch origin master
git merge -m "semiautomated-merge" origin/master
git push origin master


