#!/usr/bin/env bash

# Author: Anshuman Dhuliya [AD] (anshumandhuliya@gmail.com)
#
# Commit and sync all git repos whose directory is suffixed with `-git`

MLOCATE_DB=$MYDATA/local/files/mlocate.db;
BKPSYSCONFIG=bkpsysconfigs;

if which $BKPSYSCONFIG; then
  $BKPSYSCONFIG;
else
  echo "ERROR: $BKPSYSCONFIG not in path!!";
  exit;
fi

# update the file database
updatedb -l 0 -o $MLOCATE_DB;

TMP_OUT_FILE=`mktemp`;
TMP_FILE=`mktemp`;
TMP_REPO_LIST=`mktemp`;

echo -e "\nStarting to sync repos";
echo -e "TMP_FILE: $TMP_FILE, TMP_OUT_FILE: $TMP_OUT_FILE";

# populate the TMP_FILE with files that end with '-git'
locate -d $MLOCATE_DB -r "-git$" > $TMP_FILE;

count=0
while read file; do
  if [[ -d "$file" && -d "$file/.git" ]]; then
    # its a directory containing another directory .git (thus it is a gitrepo)
    if [[ ${file:0:5} == "/home" ]]; then
      # must be in /home sub directory tree
      count=$((count+1));
      echo "$file" >> $TMP_REPO_LIST;
      cd $file;
      echo -e "\n\nSyncing repo: `pwd`" |& tee -a $TMP_OUT_FILE;
      gitsync |& tee -a $TMP_OUT_FILE;
    fi
  fi
done < $TMP_FILE;

echo -e "\n\nRepos synced:\n";
cat $TMP_REPO_LIST;
echo -e "\nSynced $count repos.";

