#!/usr/bin/env bash

# Helps take the screeshot of a user selectable rectangle
# in the screen.
# Recommended shortcut: <shift><super>s

DATE=`date +%Y%m%d_%H%M%S`
DEST="$HOME/screen_$DATE.png"

import $DEST;
