#!/usr/bin/env bash

#DependsOn: xsel
#KeyboardShortcut: Mod-V

# Copies the text highlighted by the mouse into $CLIPBOARD_FILE

CLIPBOARD_FILE=$ITSOFLIFE/knotes-git/clipboard.txt;

#echo ""  >> $CLIPBOARD_FILE;
xsel      >> $CLIPBOARD_FILE;
echo ""   >> $CLIPBOARD_FILE;
