#!/bin/bash

mkdir thumbnails

for img in `ls *.JPG`; do
    w=`identify -format '%w' $img`
    h=`identify -format '%h' $img`
    if [ $w -lt $h ]; then
        convert -thumbnail 480 $img thumbnails/thumb.$img;
    else
        convert -thumbnail 720 $img thumbnails/thumb.$img;
    fi
done


