#!/usr/bin/env bash

# execute `crontab -e` as a non-root user
# add the line: `@reboot /home/codeman/.itsoflife/git/bin-git/startup/tiddlywiki`

# Pre-requisites/ dependencies:
# 1. Install `nodejs` and its pacakge manager `npm`.
#   sudo apt-get install nodejs
#   sudo apt-get install npm
# 2. Install tiddlywiki and test if installed
#   sudo npm install -g tiddlywiki
#   tiddlywiki --version

MYDATA=/home/codeman/.itsoflife

cd $MYDATA/git/research/writeups/research-notes-git/tiddlywiki

# starts server on the current device only.
# tiddlywiki mynewwiki --server 5050 >> $MYDATA/local/logs/tiddlywiki/tiddlywiki.log 2>&1 &

echo `date` >> $MYDATA/local/logs/tiddlywiki/tiddlywiki.log

# starts server on all availabe ips making it accessible from other computers on the network.
# it also sets the username and the password.
tiddlywiki mynewwiki --server 5050 $:/core/save/all text/plain text/html mywiki01 record482 0.0.0.0 >> $MYDATA/local/logs/tiddlywiki/tiddlywiki.log 2>&1 &
echo "Started tiddlywiki" >> $MYDATA/local/logs/tiddlywiki/tiddlywiki.log

cd others

python3 -m http.server 5051 >> $MYDATA/local/logs/tiddlywiki/tiddlywiki-others.log 2>&1 &
echo "Started python3 server" >> $MYDATA/local/logs/tiddlywiki/tiddlywiki.log


